import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

class Day07Tests {

    val input = """
        .......S.......
        ...............
        .......^.......
        ...............
        ......^.^......
        ...............
        .....^.^.^.....
        ...............
        ....^.^...^....
        ...............
        ...^.^...^.^...
        ...............
        ..^...^.....^..
        ...............
        .^.^.^.^.^...^.
        ...............
    """.trimIndent().lines()

    val inputWithTracedTachyons = """
        .......S.......
        .......|.......
        ......|^|......
        ......|.|......
        .....|^|^|.....
        .....|.|.|.....
        ....|^|^|^|....
        ....|.|.|.|....
        ...|^|^|||^|...
        ...|.|.|||.|...
        ..|^|^|||^|^|..
        ..|.|.|||.|.|..
        .|^|||^||.||^|.
        .|.|||.||.||.|.
        |^|^|^|^|^|||^|
        |.|.|.|.|.|||.|
    """.trimIndent().lines()

    @Test
    fun `Count split tachyon beams`() {
        val splitTachyons = countSplitBeams(input)
        assertThat(splitTachyons).isEqualTo(21)
    }

    @Test
    fun `Count possible routes`() {
        val possibleRoutes = countPossibleRoutes(inputWithTracedTachyons)
        assertThat(possibleRoutes).isEqualTo(40)
    }
}